version: '3.4'

services:
  site:
    image: ${WORDPRESS_IMAGE}
    depends_on:
      - database
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./${DOCKER_VOLUME_APP}:/var/www/html
    environment:
      WORDPRESS_DB_HOST: "database"
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE_NAME}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "${SITE_URL}"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

  database:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    volumes:
      - ./.${DOCKER_VOLUME_DB}:/var/lib/mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "${SITE_URL}"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - "${PHP_MY_ADMIN_PORT}:80"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: database
    healthcheck:
      test: ["CMD", "curl", "-f", "${SITE_URL}"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 0s
